/**
 * Ders çalışma / kitap okuma odak müzikleri — klasik, enstrümantal, sözsüz.
 * Her biri Spotify playlist/album ID'si (embed için).
 */
export interface FocusTrack {
  id: string;
  title: string;
  playlistId: string;
  type: "playlist" | "album";
}

const BASE = "https://open.spotify.com/embed";

export const FOCUS_MUSIC: FocusTrack[] = [
  { id: "1", title: "Peaceful Piano", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "2", title: "Classical Essentials", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "3", title: "Feel Good Classical", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "4", title: "Deep Focus", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "5", title: "Instrumental Study", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "6", title: "Piano in the Background", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "7", title: "Klasik Odak", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "8", title: "Sakin Piyano", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "9", title: "Çalışma İçin Klasik", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "10", title: "Okuma Müziği", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "11", title: "Enstrümantal Odak", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "12", title: "Bach & Piyano", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "13", title: "Ambient Çalışma", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "14", title: "Klasik Başyapıtlar", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "15", title: "Piyano Meditasyon", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "16", title: "Lo-Fi Beats", playlistId: "37i9dQZF1DWWQRwui0ExPn", type: "playlist" },
  { id: "17", title: "Jazz Vibes", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "18", title: "Odak Akışı", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "19", title: "Kitaplık Sessizliği", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "20", title: "Minimal Piyano", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "21", title: "Barok Klasik", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "22", title: "Post-Rock Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "23", title: "Yazı Yazarken", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "24", title: "Chopin & Romantik", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "25", title: "Sabah Odak", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "26", title: "Gece Çalışması", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "27", title: "Konsantrasyon", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "28", title: "Akademik Odak", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "29", title: "Soft Piano", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "30", title: "Ambient Study", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "31", title: "Klasik Piyano Seçkisi", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "32", title: "Ders Çalışma", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "33", title: "Sözsüz Müzik", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "34", title: "Beethoven Odak", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "35", title: "Rahat Piyano", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "36", title: "Lo-Fi Study", playlistId: "37i9dQZF1DWWQRwui0ExPn", type: "playlist" },
  { id: "37", title: "Kitaplık Atmosferi", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "38", title: "Derin Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "39", title: "Piyano Arka Plan", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "40", title: "Enstrümantal Klasik", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "41", title: "Sakin Klasik", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "42", title: "Odak Müziği", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "43", title: "Piyano & Okuma", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "44", title: "Ambient Piyano", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "45", title: "Klasik Okuma", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "46", title: "Çalışma Odak", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "47", title: "Minimal Klasik", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "48", title: "Post-Rock Study", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "49", title: "Piyano Dinletisi", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "50", title: "Klasik Dinleme", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "51", title: "Odaklanma", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "52", title: "Sessiz Piyano", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "53", title: "Enstrümantal Çalışma", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "54", title: "Klasik Seçkisi", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "55", title: "Lo-Fi Odak", playlistId: "37i9dQZF1DWWQRwui0ExPn", type: "playlist" },
  { id: "56", title: "Rahatlatıcı Piyano", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "57", title: "Ambient Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "58", title: "Barok Odak", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "59", title: "Piyano Çalışma", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "60", title: "Klasik Arka Plan", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "61", title: "Derin Çalışma", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "62", title: "Soft Study", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "63", title: "Piyano & Klasik", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "64", title: "Okuma Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "65", title: "Klasik Piyano", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "66", title: "Minimal Odak", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "67", title: "Hafif Klasik", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "68", title: "Piyano Sessizliği", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "69", title: "Çalışma Müziği", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "70", title: "Enstrümantal Odak", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "71", title: "Klasik Konsantrasyon", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "72", title: "Peaceful Study", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "73", title: "Ambient Piyano", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "74", title: "Odak Çalışma", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "75", title: "Romantik Klasik", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "76", title: "Piyano Odak", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "77", title: "Lo-Fi Çalışma", playlistId: "37i9dQZF1DWWQRwui0ExPn", type: "playlist" },
  { id: "78", title: "Klasik Ders", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "79", title: "Sakin Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "80", title: "Piyano Dinle", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "81", title: "Enstrümantal Klasik", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "82", title: "Deep Study", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "83", title: "Klasik Piyano Odak", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "84", title: "Rahat Klasik", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "85", title: "Odak Listesi", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "86", title: "Piyano Arka Plan Odak", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "87", title: "Klasik Başyapıtlar Odak", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "88", title: "Çalışma İçin Enstrümantal", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "89", title: "Ambient Odaklanma", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "90", title: "Piyano & Odak", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "91", title: "Klasik Okuma Listesi", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "92", title: "Sözsüz Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "93", title: "Piyano Study", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "94", title: "Feel Good Study", playlistId: "37i9dQZF1DX5Lm1ZiObdc3", type: "playlist" },
  { id: "95", title: "Instrumental Odak", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
  { id: "96", title: "Klasik Müzik Odak", playlistId: "37i9dQZF1DWWEJlAGA9gs0", type: "playlist" },
  { id: "97", title: "Peaceful Odak", playlistId: "37i9dQZF1DX4sWSpwq3LiO", type: "playlist" },
  { id: "98", title: "Deep Focus Odak", playlistId: "37i9dQZF1DWZeKCadgRdKQ", type: "playlist" },
  { id: "99", title: "Piyano Klasik", playlistId: "37i9dQZF1DX3PFzdbtx1U4", type: "playlist" },
  { id: "100", title: "Odak ve Okuma", playlistId: "37i9dQZF1DX9sIqqvKsjG8", type: "playlist" },
];

export function getEmbedUrl(track: FocusTrack): string {
  return `${BASE}/${track.type}/${track.playlistId}?theme=0`;
}
